2025-06-19 14:53:48,958 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:53:49,162 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 14:53:52,053 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:53:52,083 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:53:52,181 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 14:53:52,231 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:53:52,316 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:53:52,319 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 14:53:53,265 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:53:53,283 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:53:53,365 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 14:53:53,379 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:53:53,403 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:53:53,419 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 14:54:35,875 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:54:35,898 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:54:36,365 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 14:54:36,382 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:54:36,442 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:54:36,450 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 14:55:04,624 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:55:04,643 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:55:05,080 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 14:55:05,085 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 14:55:05,138 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 14:55:05,140 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 14:55:59,246 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 14:56:00,552 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 14:56:02,183 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 14:56:02,193 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 14:59:36,546 ERROR: API connection failed: HTTPSConnectionPool(host='api-atlas.nomic.ai', port=443): Max retries exceeded with url: /v1/embedding/text (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)'))) [in /app/app/services/chatbot_service.py:122]
2025-06-19 15:01:06,394 ERROR: API connection failed: HTTPSConnectionPool(host='api-atlas.nomic.ai', port=443): Max retries exceeded with url: /v1/user (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1147)'))) [in /app/app/services/chatbot_service.py:122]
2025-06-19 15:02:51,699 ERROR: API connection failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) [in /app/app/services/chatbot_service.py:122]
2025-06-19 15:09:35,118 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:09:35,126 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:09:35,126 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:09:35,136 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:09:39,952 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:09:39,952 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:09:39,952 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:09:39,952 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:10:05,681 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:10:05,733 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:10:05,777 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:10:16,142 INFO: Document path: app/IqbalAI_FAQ.pdf [in /app/app/services/chatbot_service.py:93]
2025-06-19 15:10:17,632 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:10:17,777 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:10:17,874 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:10:24,652 INFO: Vector store initialized. [in /app/app/services/chatbot_service.py:120]
2025-06-19 15:10:53,383 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 15:10:53,430 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 15:10:54,246 ERROR: Error loading shared vector store: Ran out of input [in /app/app/models/models.py:646]
2025-06-19 15:10:54,297 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 15:10:54,300 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 15:10:54,466 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 15:10:54,532 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 15:11:41,639 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 15:11:41,897 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 15:11:43,147 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 15:11:43,280 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 15:11:43,928 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 15:11:43,960 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 15:17:23,925 ERROR: Error in generate_response: Error code: 413 - {'error': {'message': 'Request too large for model `llama-3.3-70b-versatile` in organization `org_01jw6kggf3exerc3qj46ynxyqe` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Requested 36689, please reduce your message size and try again. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}} [in /app/app/models/models.py:529]
2025-06-19 15:17:23,971 ERROR: Error processing message: Error code: 413 - {'error': {'message': 'Request too large for model `llama-3.3-70b-versatile` in organization `org_01jw6kggf3exerc3qj46ynxyqe` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Requested 36689, please reduce your message size and try again. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}} [in /app/app/services/chat_service.py:377]
2025-06-19 15:17:24,042 ERROR: Error generating response: Error code: 413 - {'error': {'message': 'Request too large for model `llama-3.3-70b-versatile` in organization `org_01jw6kggf3exerc3qj46ynxyqe` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Requested 36689, please reduce your message size and try again. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}} [in /app/app/routes/chat.py:101]
2025-06-19 15:17:50,403 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 15:17:50,440 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 15:17:51,042 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 15:17:51,242 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 15:17:51,361 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 15:17:51,384 INFO: User 11 has not submitted the survey [in /app/app/routes/chat.py:288]
2025-06-19 15:18:52,158 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
2025-06-19 15:18:52,414 INFO: Survey check result: User 11 has not submitted a survey (count: 0) [in /app/app/models/models.py:996]
2025-06-19 15:18:54,828 INFO: Checking survey status for user_id: 11 [in /app/app/routes/chat.py:283]
2025-06-19 15:18:54,836 INFO: Checking survey submission status for user_id: 11 [in /app/app/models/models.py:987]
